config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.erp.views.tests.views import TestView, TestClientView
from core.homepage.views import IndexView

from django.conf import settings
from django.conf.urls.static import static

from core.login.views import LoginFormView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('login/', include('core.login.urls')),
    path('reports/', include('core.reports.urls')),
    # path('', IndexView.as_view(), name='index'),
    path('', LoginFormView.as_view(), name='index'),
    path('test/', TestView.as_view(), name='test'),
    path('testClient/', TestClientView.as_view(), name='testClient'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.abono.views import AbonoListView, AbonoCreateView, AbonoUpdateView, AbonoDeleteView
from core.erp.views.category.views import CategoryCreateView, CategoryListView, CategoryUpdateView, CategoryDeleteView
from core.erp.views.clientPending.views import ClientPendingListView, ClientPendingDeleteView, ClientPendingListPdf, \
    ClientPendingDeleteAllView
from core.erp.views.dashboard.views import DashboardView
from core.erp.views.equipRemove.views import EquipRemoveListView, EquipRemovePdfView
from core.erp.views.equipSuspend.views import EquipSuspendListView
from core.erp.views.invoice.views import InvoiceListView, InvoiceCreateView, InvoiceDeleteView, InvoicePdfView
from core.erp.views.jobTecnic.views import JobTecnicCreateView, JobTecnicListView, JobTecnicUpdateView, \
    JobTecnicDeleteView, JobTecnicMonthlyPlanning
from core.erp.views.pay.views import PayListView, PayCreateView, PayUpdateView, PayDeleteView, PayPrintPdfView, \
    PayCreateViewTest
from core.erp.views.product.views import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView
from core.erp.views.client.views import *
from core.erp.views.sale.views import SaleCreateView, SaleListView, SaleDeleteView, SaleInvoicePdfView
from core.erp.views.tecnic.views import TecnicListView, TecnicCreateView, TecnicUpdateView, TecnicDeleteView
from core.erp.views.tests.views import TestView
from core.erp.views.zone.views import ZoneListView, ZoneCreateView, ZoneDeleteView, ZoneUpdateView, ZoneRoutePdfView, \
    ZoneOrderView

app_name = 'erp'

urlpatterns = [
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # client
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/add/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('client/saldos/', ClientSaldoView.as_view(), name='client_saldos'),
    path('client/saldos/pdf/<int:ti>/<int:zi>/<str:t_pay>/<str:d_start>/<str:d_end>/', ClientSaldoPdf.as_view(),
         name='client_saldos_pdf'),
    # abono
    path('abono/list/', AbonoListView.as_view(), name='abono_list'),
    path('abono/add/', AbonoCreateView.as_view(), name='abono_create'),
    path('abono/update/<int:pk>/', AbonoUpdateView.as_view(), name='abono_update'),
    path('abono/delete/<int:pk>/', AbonoDeleteView.as_view(), name='abono_delete'),
    # tecnic
    path('tecnic/list/', TecnicListView.as_view(), name='tecnic_list'),
    path('tecnic/add/', TecnicCreateView.as_view(), name='tecnic_create'),
    path('tecnic/update/<int:pk>/', TecnicUpdateView.as_view(), name='tecnic_update'),
    path('tecnic/delete/<int:pk>/', TecnicDeleteView.as_view(), name='tecnic_delete'),
    # category
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # sale
    path('sale/list/', SaleListView.as_view(), name='sale_list'),
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/invoice/pdf/<int:pk>/', SaleInvoicePdfView.as_view(), name='sale_invoice_pdf'),
    # zone
    path('zone/list/', ZoneListView.as_view(), name='zone_list'),
    path('zone/add/', ZoneCreateView.as_view(), name='zone_create'),
    path('zone/update/<int:pk>/', ZoneUpdateView.as_view(), name='zone_update'),
    path('zone/delete/<int:pk>/', ZoneDeleteView.as_view(), name='zone_delete'),
    path('zone/route/pdf/<int:pk>/', ZoneRoutePdfView.as_view(), name='zone_route'),
    path('zone/orderzone/<int:pk>/', ZoneOrderView.as_view(), name='zone_order'),
    # pay
    path('pay/list/', PayListView.as_view(), name='pay_list'),
    path('pay/add/', PayCreateView.as_view(), name='pay_create'),
    path('pay/add/test/', PayCreateViewTest.as_view(), name='pay_create_test'),
    path('pay/update/<int:pk>/', PayUpdateView.as_view(), name='pay_update'),
    path('pay/delete/<int:pk>/', PayDeleteView.as_view(), name='pay_delete'),
    path('pay/print/pdf/<int:pk>/', PayPrintPdfView.as_view(), name='sale_invoice_pdf'),
    # invoice
    path('invoice/list/', InvoiceListView.as_view(), name='invoice_list'),
    path('invoice/add/', InvoiceCreateView.as_view(), name='invoice_create'),
    path('invoice/delete/<int:pk>/', InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('invoice/pdf/<int:pk>/', InvoicePdfView.as_view(), name='invoice_pdf'),
    # jobTecnic
    path('jobTecnic/list/', JobTecnicListView.as_view(), name='jobTecnic_list'),
    path('jobTecnic/add/', JobTecnicCreateView.as_view(), name='jobTecnic_create'),
    path('jobTecnic/update/<int:pk>/', JobTecnicUpdateView.as_view(), name='jobTecnic_update'),
    path('jobTecnic/delete/<int:pk>/', JobTecnicDeleteView.as_view(), name='jobTecnic_delete'),
    path('jobTecnic/month-planning/', JobTecnicMonthlyPlanning.as_view(), name='jobTecnicMonthPlanning_list'),
    # clientPending
    path('clientPending/list/', ClientPendingListView.as_view(), name='clientPending_list'),
    path('clientPending/delete/<int:pk>/', ClientPendingDeleteView.as_view(), name='clientPending_delete'),
    path('clientPending/delete/all/', ClientPendingDeleteAllView.as_view(), name='clientPending_delete_all'),
    path('clientPending/list/pdf/<int:ti>/', ClientPendingListPdf.as_view(), name='clientPending_list_pdf'),
    # equipRemove
    path('equipRemove/list/', EquipRemoveListView.as_view(), name='equipRemove_list'),
    path('equipRemove/pdf/<int:pk>/', EquipRemovePdfView.as_view(), name='equipRemove_pdf'),
    # equipSuspend
    path('equipSuspend/list/', EquipSuspendListView.as_view(), name='equipSuspend_list'),
    # test
    path('test/', TestView.as_view(), name='test_view'),
]

templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido
                                <small>{{ request.user.first_name }} {{ request.user.last_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}

    <script>
        {#muestra los mensajes devueltos por el dispath en el mixin de validacion de permisos#}
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            {#utilizamos la libreria sweetAlert#}
            Swal.fire({
                icon: 'error',
                title: 'Error!',
                html: html
            });
        {% endif %}
    </script>

    </body>
{% endblock %}

templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-lightblue">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'erp:dashboard' %}" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i> {{ request.user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">
                        Último Acceso: {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i> Salir
            </a>
        </li>
    </ul>
</nav>

templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="#" class="brand-link">
        <img src="{% static 'img/crm-logo-2.jpg' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">GESTIÓN</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.first_name }} {{ request.user.last_name }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Gestion</li>
                <li class="nav-item">
                    <a href="{% url 'erp:dashboard' %}" class="nav-link">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Menú Principal
                        </p>
                    </a>
                </li>
                {# menu clientes#}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-address-book"></i>
                        <p>
                            Clientes
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none; padding-left: 30px">
                        <li class="nav-item">
                            <a href="{% url 'erp:client_list' %}" class="nav-link">
                                <i class="fas fa-address-book nav-icon"></i>
                                <p>Agenda</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:client_saldos' %}" class="nav-link">
                                <i class="nav-icon fas fa-search-dollar"></i>
                                <p>Listado de Saldos</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:equipRemove_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-ban"></i>
                                <p>Listado de Retiros</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:equipSuspend_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-clock"></i>
                                <p>Listado de Suspendidos</p>
                            </a>
                        </li>
                    </ul>
                </li>
                {# menu gestion#}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tools"></i>
                        <p>
                            Gestion
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none; padding-left: 30px">
                        <li class="nav-item">
                            <a href="{% url 'erp:abono_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-money-check-alt"></i>
                                <p>Abonos</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:category_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-clipboard-list"></i>
                                <p>Categorias</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:product_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-boxes"></i>
                                <p>Productos</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-building"></i>
                                <p>Empresa</p>
                            </a>
                        </li>
                    </ul>
                </li>
                {# menu facturacion#}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-balance-scale"></i>
                        <p>
                            Facturación
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none; padding-left: 30px">
                        <li class="nav-item">
                            <a href="{% url 'erp:invoice_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-file-invoice-dollar"></i>
                                <p>Servicios Mensuales</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:sale_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-shopping-cart"></i>
                                <p>Ventas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'sale_report' %}" class="nav-link">
                                <i class="nav-icon fas fa-chart-line"></i>
                                <p>Reportes</p>
                            </a>
                        </li>
                    </ul>
                </li>
                {# menu tecnicos#}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-users-cog"></i>
                        <p>
                            Técnicos
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none; padding-left: 30px">
                        <li class="nav-item">
                            <a href="{% url 'erp:jobTecnic_create' %}" class="nav-link">
                                <i class="nav-icon fas fa-briefcase"></i>
                                <p>Cargar trabajo</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:pay_create' %}" class="nav-link">
                                <i class="nav-icon fas fa-hand-holding-usd"></i>
                                <p>Cargar Cobranza</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:clientPending_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-business-time"></i>
                                <p>Clientes Pendientes</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:pay_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-folder-open"></i>
                                <p>Historial de Cobranzas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:tecnic_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-user-tie"></i>
                                <p>Listado de Técnicos</p>
                            </a>
                        </li>
                    </ul>
                </li>
                {# menu zonas#}
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-network-wired"></i>
                        <p>
                            Zonas
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none; padding-left: 30px">
                        <li class="nav-item">
                            <a href="{% url 'erp:zone_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-list-ol"></i>
                                <p>Listado de Zonas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:jobTecnicMonthPlanning_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-calendar-check"></i>
                                <p>Planificación de Zonas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:jobTecnic_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-folder-open"></i>
                                <p>Historial de Zonas</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>