config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.erp.views.tests.views import TestView, TestClientView
from core.homepage.views import IndexView

from django.conf import settings
from django.conf.urls.static import static

from core.login.views import LoginFormView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('login/', include('core.login.urls')),
    path('reports/', include('core.reports.urls')),
    # path('', IndexView.as_view(), name='index'),
    path('', LoginFormView.as_view(), name='index'),
    path('test/', TestView.as_view(), name='test'),
    path('testClient/', TestClientView.as_view(), name='testClient'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.abono.views import AbonoListView, AbonoCreateView, AbonoUpdateView, AbonoDeleteView
from core.erp.views.category.views import CategoryCreateView, CategoryListView, CategoryUpdateView, CategoryDeleteView
from core.erp.views.clientPending.views import ClientPendingListView, ClientPendingDeleteView, ClientPendingListPdf, \
    ClientPendingDeleteAllView
from core.erp.views.dashboard.views import DashboardView
from core.erp.views.equipRemove.views import EquipRemoveListView, EquipRemovePdfView
from core.erp.views.equipSuspend.views import EquipSuspendListView
from core.erp.views.invoice.views import InvoiceListView, InvoiceCreateView, InvoiceDeleteView, InvoicePdfView
from core.erp.views.jobTecnic.views import JobTecnicCreateView, JobTecnicListView, JobTecnicUpdateView, \
    JobTecnicDeleteView, JobTecnicMonthlyPlanning
from core.erp.views.pay.views import PayListView, PayCreateView, PayUpdateView, PayDeleteView, PayPrintPdfView, \
    PayCreateViewTest
from core.erp.views.product.views import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView
from core.erp.views.client.views import *
from core.erp.views.sale.views import SaleCreateView, SaleListView, SaleDeleteView, SaleInvoicePdfView
from core.erp.views.tecnic.views import TecnicListView, TecnicCreateView, TecnicUpdateView, TecnicDeleteView
from core.erp.views.tests.views import TestView
from core.erp.views.zone.views import ZoneListView, ZoneCreateView, ZoneDeleteView, ZoneUpdateView, ZoneRoutePdfView, \
    ZoneOrderView

app_name = 'erp'

urlpatterns = [
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # client
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/add/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('client/saldos/', ClientSaldoView.as_view(), name='client_saldos'),
    path('client/saldos/pdf/<int:ti>/<int:zi>/<str:t_pay>/<str:d_start>/<str:d_end>/', ClientSaldoPdf.as_view(),
         name='client_saldos_pdf'),
    # abono
    path('abono/list/', AbonoListView.as_view(), name='abono_list'),
    path('abono/add/', AbonoCreateView.as_view(), name='abono_create'),
    path('abono/update/<int:pk>/', AbonoUpdateView.as_view(), name='abono_update'),
    path('abono/delete/<int:pk>/', AbonoDeleteView.as_view(), name='abono_delete'),
    # tecnic
    path('tecnic/list/', TecnicListView.as_view(), name='tecnic_list'),
    path('tecnic/add/', TecnicCreateView.as_view(), name='tecnic_create'),
    path('tecnic/update/<int:pk>/', TecnicUpdateView.as_view(), name='tecnic_update'),
    path('tecnic/delete/<int:pk>/', TecnicDeleteView.as_view(), name='tecnic_delete'),
    # category
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # sale
    path('sale/list/', SaleListView.as_view(), name='sale_list'),
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/invoice/pdf/<int:pk>/', SaleInvoicePdfView.as_view(), name='sale_invoice_pdf'),
    # zone
    path('zone/list/', ZoneListView.as_view(), name='zone_list'),
    path('zone/add/', ZoneCreateView.as_view(), name='zone_create'),
    path('zone/update/<int:pk>/', ZoneUpdateView.as_view(), name='zone_update'),
    path('zone/delete/<int:pk>/', ZoneDeleteView.as_view(), name='zone_delete'),
    path('zone/route/pdf/<int:pk>/', ZoneRoutePdfView.as_view(), name='zone_route'),
    path('zone/orderzone/<int:pk>/', ZoneOrderView.as_view(), name='zone_order'),
    # pay
    path('pay/list/', PayListView.as_view(), name='pay_list'),
    path('pay/add/', PayCreateView.as_view(), name='pay_create'),
    path('pay/add/test/', PayCreateViewTest.as_view(), name='pay_create_test'),
    path('pay/update/<int:pk>/', PayUpdateView.as_view(), name='pay_update'),
    path('pay/delete/<int:pk>/', PayDeleteView.as_view(), name='pay_delete'),
    path('pay/print/pdf/<int:pk>/', PayPrintPdfView.as_view(), name='sale_invoice_pdf'),
    # invoice
    path('invoice/list/', InvoiceListView.as_view(), name='invoice_list'),
    path('invoice/add/', InvoiceCreateView.as_view(), name='invoice_create'),
    path('invoice/delete/<int:pk>/', InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('invoice/pdf/<int:pk>/', InvoicePdfView.as_view(), name='invoice_pdf'),
    # jobTecnic
    path('jobTecnic/list/', JobTecnicListView.as_view(), name='jobTecnic_list'),
    path('jobTecnic/add/', JobTecnicCreateView.as_view(), name='jobTecnic_create'),
    path('jobTecnic/update/<int:pk>/', JobTecnicUpdateView.as_view(), name='jobTecnic_update'),
    path('jobTecnic/delete/<int:pk>/', JobTecnicDeleteView.as_view(), name='jobTecnic_delete'),
    path('jobTecnic/month-planning/', JobTecnicMonthlyPlanning.as_view(), name='jobTecnicMonthPlanning_list'),
    # clientPending
    path('clientPending/list/', ClientPendingListView.as_view(), name='clientPending_list'),
    path('clientPending/delete/<int:pk>/', ClientPendingDeleteView.as_view(), name='clientPending_delete'),
    path('clientPending/delete/all/', ClientPendingDeleteAllView.as_view(), name='clientPending_delete_all'),
    path('clientPending/list/pdf/<int:ti>/', ClientPendingListPdf.as_view(), name='clientPending_list_pdf'),
    # equipRemove
    path('equipRemove/list/', EquipRemoveListView.as_view(), name='equipRemove_list'),
    path('equipRemove/pdf/<int:pk>/', EquipRemovePdfView.as_view(), name='equipRemove_pdf'),
    # equipSuspend
    path('equipSuspend/list/', EquipSuspendListView.as_view(), name='equipSuspend_list'),
    # test
    path('test/', TestView.as_view(), name='test_view'),
]

core/erp/models.py
from datetime import datetime

from crum import get_current_user
from django.utils import timezone

from config.settings import MEDIA_URL, STATIC_URL
from django.db import models
from django.forms import model_to_dict

from core.models import BaseModel

import locale
# locale.setlocale(locale.LC_TIME, 'es-AR')


class Abono(models.Model):
    choices_type_abono = (('Od', 'Odorizador'), ('Ae', 'Aerosol'), ('Go', 'Goteo'))

    name = models.CharField(max_length=50, verbose_name='Nombre del Abono')
    type = models.CharField(choices=choices_type_abono, max_length=2, default='Od', null=True, blank=True, verbose_name='Tipo Abono')
    price = models.FloatField(default=0.00, verbose_name='Precio del Abono')
    description = models.CharField(max_length=200, verbose_name='Descripción del Abono', null=True, blank=True)
    date_created = models.DateField(editable=False, verbose_name='Fecha Creación de Abono')
    date_updated = models.DateField(verbose_name='Fecha Actualización de Abono')

    def __str__(self):
        return self.name

    def toJSON(self):
        # convierte todos los campos de el objeto en un diccionario y los asigna a la variable
        item = model_to_dict(self)
        item['price'] = format(self.price, '.2f')
        item['type'] = self.get_type_display()
        item['date_created'] = self.date_created.strftime('%d/%m/%y').capitalize()
        item['date_updated'] = self.date_updated.strftime('%d/%m/%y').capitalize()
        return item

    class Meta:
        verbose_name = 'Abono'
        verbose_name_plural = 'Abonos'
        ordering = ['id']

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.date_created = timezone.now()
        self.date_updated = timezone.now()
        return super(Abono, self).save(*args, **kwargs)


class Tecnic(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Nombre Tecnico')
    desc = models.CharField(max_length=500, null=True, blank=True, verbose_name='Descripción')

    def __str__(self):
        return self.name

    def toJSON(self):
        # convierte todos los campos de el objeto en un diccionario y los asigna a la variable
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Tecnico'
        verbose_name_plural = 'Tecnicos'
        ordering = ['id']


class Zone(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nombre de la zona')
    tecnic = models.ForeignKey(Tecnic, on_delete=models.CASCADE, verbose_name='Nombre del Tecnico', blank=True, null=True,)
    desc = models.CharField(max_length=500, null=True, blank=True, verbose_name='Descripción')
    dateWork = models.DateField(default=datetime.now, verbose_name="Fecha de realizacion")
    enable = models.BooleanField(default=True, verbose_name='Habilitado')

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        item['tecnic'] = self.tecnic.toJSON()
        return item

    class Meta:
        verbose_name = 'Zona'
        verbose_name_plural = 'Zonas'
        ordering = ['id']


class Client(BaseModel):
    choices_type_pay = (('Ef', 'Efectivo'), ('Tr', 'Transferencia'), ('Ch', 'Cheque'))

    name = models.CharField(max_length=150, verbose_name='Nombre o Razon Social')
    cuit = models.CharField(max_length=11, null=True, blank=True, verbose_name='Cuit')
    address = models.CharField(max_length=150, null=True, blank=True, verbose_name='Domicilio')
    address_invoice = models.CharField(max_length=150, null=True, blank=True, verbose_name='Domicilio Factura')
    phone = models.CharField(max_length=150, null=True, blank=True, verbose_name='Telefono')
    contact = models.CharField(max_length=150, null=True, blank=True, verbose_name='Nombre de Contacto')
    email = models.EmailField(null=True, blank=True, verbose_name='Correo Electronico')
    schedule = models.CharField(max_length=150, null=True, blank=True, verbose_name='Horario')
    description = models.TextField(null=True, blank=True, verbose_name='Descripción')
    type_pay = models.CharField(choices=choices_type_pay, max_length=2, default='Ef', null=True, blank=True, verbose_name='Tipo_pago')
    tecnic = models.ForeignKey(Tecnic, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Nombre de Tecnico', default=1)
    zone = models.ForeignKey(Zone, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Nombre de Zona', default=1)
    position = models.IntegerField(default=99, null=True, blank=True, verbose_name='Posicion')
    enable = models.BooleanField(default=True, verbose_name='Habilitado')
    active = models.BooleanField(default=True, verbose_name='Activado')
    # falta agregar cliente a una empresa (se implementara igual que services, con betterform)

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        super(Client, self).save()

    def toJSON(self):
        # convierte todos los campos de el objeto en un diccionario y los asigna a la variable
        item = model_to_dict(self, exclude=['user_creation', 'user_update'])
        item['tecnic'] = self.tecnic.toJSON()
        if self.zone:
            item['zone'] = self.zone.toJSON()
        else:
            item['zone'] = {"name": "N/A"}
        return item

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['id']


class Services(models.Model):
    cli = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Nombre de cliente')
    odorizador = models.ForeignKey(Abono, related_name='related_odorizador_abono',  on_delete=models.SET_NULL, verbose_name='Abono Odorizador', blank=True, null=True)
    cant_odo = models.IntegerField(default=0, verbose_name='Cantidad Odorizadores')
    aerosoles = models.ForeignKey(Abono, related_name='related_aerosoles_abono', on_delete=models.SET_NULL, verbose_name='Abono Aerosoles', blank=True, null=True)
    cant_aer = models.IntegerField(default=0, verbose_name='Cantidad Aerosoles')
    goteos = models.ForeignKey(Abono, related_name='related_goteos_abono', on_delete=models.SET_NULL, verbose_name='Abono Goteos', blank=True, null=True)
    cant_got = models.IntegerField(default=0, verbose_name='Cantidad Goteos')

    def __str__(self):
        return self.cli.name

    def toJSON(self):
        # convierte todos los campos de el objeto en un diccionario y los asigna a la variable
        item = model_to_dict(self)
        item['cli'] = self.cli.toJSON()
        if self.odorizador:
            item['odorizador'] = self.odorizador.toJSON()
        if self.aerosoles:
            item['aerosoles'] = self.aerosoles.toJSON()
        if self.goteos:
            item['goteos'] = self.goteos.toJSON()
        return item

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'
        ordering = ['id']


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre', unique=True)
    desc = models.CharField(max_length=500, null=True, blank=True, verbose_name='Descripción')

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nombre', unique=True)
    cat = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categoría')
    image = models.ImageField(upload_to='product/%Y/%m/%d', null=True, blank=True, verbose_name='Imagen')
    pvp = models.DecimalField(default=0.00, max_digits=9, decimal_places=2, verbose_name='Precio de venta')

    def __str__(self):
        return self.name

    def toJSON(self):
        item = model_to_dict(self)
        item['cat'] = self.cat.toJSON()
        item['image'] = self.get_image()
        item['pvp'] = format(self.pvp, '.2f')
        return item

    def get_image(self):
        if self.image:
            return '{}{}'.format(MEDIA_URL, self.image)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']


class Invoice(models.Model):
    cli = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Cliente')
    date_joined = models.DateField(default=datetime.now, verbose_name='Fecha de Factura')
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    iva = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    type = models.CharField(max_length=20, verbose_name='Tipo')

    def __str__(self):
        return str(self.id)

    def toJSON(self):
        item = model_to_dict(self)
        item['cli'] = self.cli.toJSON()
        item['subtotal'] = format(self.subtotal, '.2f')
        item['iva'] = format(self.iva, '.2f')
        item['total'] = format(self.total, '.2f')
        item['date_joined'] = self.date_joined.strftime('%B %y').capitalize()
        # lo utilizo para poder llamarlo desde la funcion format en el datatable de la venta y mostrarlo en "child row"
        item['det'] = [i.toJSON() for i in self.detinvoice_set.all()]
        item['type'] = self.type
        item['invoice_id'] = self.id
        return item

    class Meta:
        verbose_name = 'Factura'
        verbose_name_plural = 'Facturas'
        ordering = ['id']


class DetInvoice(models.Model):

core/erp/templates/zone/create.html
{% extends 'form.html' %}

{% block field_enable %}

    <div class="form-group">
        <div class="custom-control custom-switch">
            {{ form.enable }}
            <label class="custom-control-label" for="id_enable" id="label">{{ form.enable.label }}</label>
            <input type="hidden" name="enableStatus" id="enableStatus" value="{{ form.enable.value }}">
        </div>
    </div>

{% endblock %}


{% block javascript %}

    <script>
        {#script para el switch de cliente habilitado#}
        var status;
        let x = document.getElementById("enableStatus").value;
        console.log(x);
        var label = document.querySelector('#label');

        if (x === 'False'){
            label.textContent = 'Deshabilitado';
        }

        $('#id_enable').click(function () {
            if (this.checked) {
                this.value = true;
                status = 'true';
                label.textContent = 'Habilitado';
            } else {
                this.value = false;
                status = 'false';
                label.textContent = 'Deshabilitado';
            }
            console.log(this.value);
        })
    </script>

{% endblock %}

core/erp/templates/zone/delete.html
{% extends 'delete.html' %}

core/erp/templates/zone/list.html
{% extends 'list.html' %}
{% load static %}

{#bloque para cargar la funcion para listar los clientes#}
{% block head_list %}
    <script src="{% static 'zone/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
    <tr>
        <th scope="col" style="width: 20%">Nombre</th>
        <th scope="col" style="width: 20%">Tecnico</th>
        <th scope="col" style="width: 20%">Descripción</th>
        <th scope="col" style="width: 15%">Opciones</th>
    </tr>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}
    <div class="modal fade" id="myModelZone" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><i class="fas fa-shopping-cart"></i> Planilla de Zona</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table class="table" id="tblZone">
                        <thead>
                        <tr>
                            <th>Posición</th>
                            <th>Nombre</th>
                            <th>Dirección</th>
                            <th>Abono</th>
                            <th>Cantidad</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/erp/templates/zone/orderZone.html
{% extends 'list.html' %}
{% load static %}

{#bloque para cargar la funcion para listar los clientes#}
{% block head_list %}
    <script src="{% static 'zone/js/orderZone.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/DataTables/RowReorder-1.2.8/RowReorder-1.2.8/css/rowReorder.bootstrap.min.css' %}">
    <script src="{% static 'lib/DataTables/RowReorder-1.2.8/RowReorder-1.2.8/js/dataTables.rowReorder.min.js' %}"></script>
{% endblock %}

{% block columns %}
    <tr>
        <th scope="col" style="width: 5%">Nro</th>
        <th scope="col" style="width: 5%">Pos</th>
        <th scope="col" style="width: 35%">Nombre</th>
        <th scope="col" style="width: 35%">Dirección</th>
        <th scope="col" style="width: 10%">Cant</th>
        <th scope="col" style="width: 20%">Abono</th>
    </tr>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}
{% endblock %}

core/erp/templates/zone/route.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>

        * {
            color: black;
        }

        body {
            font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
            padding: 0;
            margin: 0;
            color: black;
        }

        .name-company {
            font-size: 20px;
            padding: 0;
            margin: 0;
            font-weight: bold;
            text-transform: uppercase;
            text-align: center;
        }

        .sale-date-joined {
            font-size: 15px;
            padding: 0;
            margin: 0;
            text-transform: uppercase;
            text-align: right;
        }

        .data-company {
            font-size: 8px;
            padding: 0;
            margin: 0;
            text-transform: uppercase;
            text-align: right;
        }

        table thead tr th {
            border: 1px solid black !important;
            padding: 3px;
        }

        table tbody tr td {
            font-size: 12px;
            border: 1px solid black;
            padding: 3px;
        }

        .img-logo {
            margin-top: 10px;
            width: 75px;
            height: 75px;
            margin-bottom: 10px;
        }

    </style>
</head>
<body>
<div class="container-fluid">
    <img src="{% static 'img/logo3.png' %}" class="img-fluid d-block mx-auto img-logo">
    {#    <h1 class="name-company">{{ comp.name }}</h1>#}
    {#    <p class="text-center data-company">#}
    {#        CUIT: {{ comp.cuit }}<br>#}
    {#        {{ comp.address }}<br>#}
    {#        Tel.: {{ comp.phone }} -#}
    {#        Web: {{ comp.web }}<br>#}
    {#    </p>#}
    {#    <hr>#}
    {#    <br>#}
{#    <p>#}
{#    <h3 class="sale-date-joined"><b>Fecha:</b> {{ date }}</h3><br>#}
{#    <b>TECNICO:</b> {{ zone.tecnic }}<br>#}
{#    <b>ZONA:</b> {{ zone.name }}<br>#}
{#    </p>#}
{#    <br>#}
    <table class="table" style="width: 100%;">
        <thead>
        <tr style="border: 1px solid black;">
            <th style="font-weight: normal; text-align: center"><b>TÉCNICO:</b> {{ zone.tecnic }}</th>
            <th style="font-weight: normal; text-align: center"><b>ZONA:</b> {{ zone.name }}</th>
            <th style="font-weight: normal; text-align: center"><b>FECHA:</b> {{ date }}</th>
        </tr>
        </thead>
    </table>
    <br>
    <table class="table" style="width: 100%;">
        <thead>
        <tr style="border: 1px solid black;">
            <th style="width: 5%;">Nro</th>
            <th style="width: 30%;" class="text-center">Cliente</th>
            <th style="width: 30%;" class="text-center">Direccion</th>
            <th style="width: 5%;">Equipos</th>
            <th style="width: 10%;" class="text-center">Abono</th>
            <th style="width: 20%;" class="text-center">Firma</th>
        </tr>
        </thead>
        <tbody>
        {% for cli in data %}
            <tr>
                {% if cli.active %}
                    <td class="text-center">{{ cli.position }}</td>
                    <td class="text-uppercase">{{ cli.name }}</td>
                    <td class="text-capitalize">{{ cli.address }}</td>
                    <td class="text-right">{{ cli.cant_odo }}</td>
                    <td class="text-right"> {{ cli.abono }} </td>
                {% endif %}
                {% if not cli.active %}
                    <td class="text-center">
                        <del>{{ cli.position }}</del>
                    </td>
                    <td>
                        <del>{{ cli.name }}</del>
                    </td>
                    <td class="text-capitalize">
                        <del>{{ cli.address }}</del>
                    </td>
                    <td class="text-right">
                        <del>{{ cli.cant_odo }}</del>
                    </td>
                    <td class="text-right">
                        <del>{{ cli.abono }}</del>
                    </td>
                {% endif %}
                <td class="text-right"></td>
            </tr>
        {% endfor %}

        <tr>
            <td colspan="6">
                <p class="text-uppercase font-weight-bold text-left">
                    <br><br>Datos de la Zona:
                </p>
                <p class="font-italic text-left">
                    <b>Cantidad Clientes:</b> {{ total_clientes }} <br>
                    <b>Cantidad Equipos:</b> {{ total_equipos }} <br>
                    <b>Total facturado mes:</b> $ {{ total_facturado }} <br>
                    <b>Deuda anterior:</b> $ <br>
                    <b>Total efectivo:</b> $ <br>
                    <b>Total deposito:</b> $ <br>
                </p>
            </td>
        </tr>
        </tbody>
    </table>
</div>
</body>
</html>